-- Phase 2 transaction persistence. Apply after the baseline schema.
create table if not exists vendors (id uuid primary key default gen_random_uuid(), project_id uuid not null references projects(id), name text not null, code text not null, unique(project_id,code));
create table if not exists contracts (id uuid primary key default gen_random_uuid(), project_id uuid not null references projects(id), vendor_id uuid not null references vendors(id), contract_no text not null, contract_value numeric(20,2) not null check(contract_value>=0), status text not null, unique(project_id,contract_no));
create table if not exists commitments (id uuid primary key default gen_random_uuid(), project_id uuid not null references projects(id), contract_id uuid references contracts(id), wbs_id uuid references wbs_nodes(id), cost_code_id uuid references cost_codes(id), reference_no text not null, vendor_name text not null, committed_amount numeric(20,2) not null check(committed_amount>=0), status text not null, unique(project_id,reference_no));
create table if not exists invoices (id uuid primary key default gen_random_uuid(), project_id uuid not null references projects(id), commitment_id uuid not null references commitments(id), invoice_no text not null, invoice_amount numeric(20,2) not null check(invoice_amount>=0), status text not null, unique(project_id,invoice_no));
create table if not exists actual_costs (id uuid primary key default gen_random_uuid(), project_id uuid not null references projects(id), period_id uuid not null references reporting_periods(id), invoice_id uuid references invoices(id), wbs_id uuid references wbs_nodes(id), cost_code_id uuid references cost_codes(id), amount numeric(20,2) not null check(amount>=0), source_ref text not null, status text not null default 'POSTED', posted_at timestamptz not null default now());
create table if not exists accruals (id uuid primary key default gen_random_uuid(), project_id uuid not null references projects(id), period_id uuid not null references reporting_periods(id), amount numeric(20,2) not null check(amount>=0), source_ref text not null, status text not null default 'DRAFT');
create index if not exists commitments_project_status on commitments(project_id,status);
create index if not exists actual_costs_project_period on actual_costs(project_id,period_id);
